---
title: "MU Analysis Non-Endemic Area"
author: "Desmond Gul"
date: "2024-03-26"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(rio)
library(here)
library(tidyverse)
library(janitor)
library(sf)

```

This is analysis for MU cases ID: MeCo 320245602429

```{r}
data_file <- "MUdata_20240325.xlsx"

mu_data_raw <- import(here("Data", data_file)) %>% 
  clean_names()

mu_exp_loc <- mu_data_raw %>% 
  select(event_id, event_date, postcode, lga, latitude, longitude, risk_factor, primary_exposure, risk_factors_exposure_site_latitude, risk_factors_exposure_site_longitude) %>% 
  mutate(event_date = lubridate::ymd(event_date)) 
```

```{r}
mu_exp.sf <- mu_exp_loc %>% 
  tidyr::drop_na(., risk_factors_exposure_site_latitude) %>% 
  st_as_sf(., coords=c("risk_factors_exposure_site_longitude", "risk_factors_exposure_site_latitude"), crs=st_crs(4326))

mu_resid.sf <- mu_exp_loc %>% 
  tidyr::drop_na(., latitude) %>% 
  filter(primary_exposure=="Primary") %>% 
  distinct(event_id, .keep_all=TRUE) %>% 
  st_as_sf(., coords=c("longitude", "latitude"), crs=4326)

```

```{r}
library(leaflet)

# format setup for mouse hover label
labels <- sprintf(
  "ID: %s<br/>Date: %s<br/>Risk: %s", 
  mu_resid.sf$event_id, mu_resid.sf$event_date, mu_resid.sf$risk_factor) %>% 
  lapply(htmltools::HTML)

leaflet(mu_resid.sf) %>% 
  addTiles() %>% 
  addMarkers(label=labels)


leaflet(mu_exp.sf) %>% 
  addTiles() %>% 
  addMarkers(popup = ~event_id) %>% 
  
  # setView(lat=-38, lng=145, zoom=10) %>% 
  addPolygons(color="#444444", weight=1, opacity=1.0, fillOpacity=0.8, smoothFactor=0.5, 
              fillColor= ~colorNumeric(rev(colorRamps::blue2red(6)), domain=pct)(pct), 
              highlightOptions = highlightOptions(color="white", weight=2, bringToFront = TRUE), 
              label = labels) %>% # alt: ~variable or ~function(vars)
  addLegend(pal = colorNumeric(rev(colorRamps::blue2red(6)), nephu_bcs2periods_poa.sf$pct), 
            values = ~nephu_bcs2periods_poa.sf$pct, title="%", opacity=1, position="bottomright")

filter(mu_resid.sf, event_id=="320235538280")

# calculate distance to nearest cases
distance_subset <- filter(mu_resid.sf, event_id %in% c("320235538280", "320245602429", "320235539939", "320235556630")) 

st_distance(distance_subset)


```

```{r}
# review the new VIC shapefiles for POA

vic_pos.shp <- st_read(here("Data", "VIC_POA_SHP/POSTCODE_POLYGON.shp"))

ggplot(vic_pos.shp) + 
  geom_sf()

abs_aus_poa.shp <- st_read(here("Data", "POA_2021_AUST_GDA2020_SHP/POA_2021_AUST_GDA2020.shp"))

abs_vic_poa.shp <- abs_aus_poa.shp %>% 
  filter(between(as.numeric(POA_CODE21), 3000, 3999)) 

ggplot(abs_vic_poa.shp) + geom_sf()
```

